module.exports = {
  purge: {
    enabled: !process.env.ROLLUP_WATCH,
    mode: 'all',
    content: ['./**/**/*.html', './**/**/*.svelte'],
  },
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {},
    flex: {
      1: '1 1 0%',
      2: '2 2 0%',
    },
  },
  variants: {
    extend: {},
  },
  plugins: [require('daisyui'), require('@tailwindcss/typography')],
  daisyui: {
    themes: [
      {
        light: {
          primary: '#54d1c3',
          'primary-focus': '#2da69a',
          'primary-content': '#ffffff',
          secondary: '#ffba23',
          'secondary-focus': '#e0a421',
          'secondary-content': '#ffffff',
          accent: '#ff4341',
          'accent-focus': '#dc3a39',
          'accent-content': '#ffffff',
          neutral: '#8d9ba9',
          'neutral-focus': '#6b7580',
          'neutral-content': '#ffffff',
          'base-100': '#ffffff',
          'base-200': '#d1d5da',
          'base-300': '#414141',
          'base-content': '#f6f7f7',
        },
      },
      {
        dark: {
          primary: '#793ef9',
          'primary-focus': '#560df8',
          'primary-content': '#ffffff',
          secondary: '#ef02b8',
          'secondary-focus': '#bc0291',
          'secondary-content': '#ffffff',
          accent: '#3acdbe',
          'accent-focus': '#2ca79b',
          'accent-content': '#ffffff',
          neutral: '#8d9ba9',
          'neutral-focus': '#6b7580',
          'neutral-content': '#ffffff',
          'base-100': '#3c4551',
          'base-200': '#15191e',
          'base-300': '#bdc0c6',
          'base-content': '#343d47',
        },
      },
      {
        halloween: {
          primary: '#f28d17',
          'primary-focus': '#ca710e',
          'primary-content': '#ffffff',
          secondary: '#6d3b9c',
          'secondary-focus': '#532c77',
          'secondary-content': '#ffffff',
          accent: '#53a803',
          'accent-focus': '#397602',
          'accent-content': '#ffffff',
          neutral: '#8d9ba9',
          'neutral-focus': '#6b7580',
          'neutral-content': '#ffffff',
          'base-100': '#222222',
          'base-200': '#545454',
          'base-300': '#ebecf0',
          'base-content': '#2c2c2c',
        },
      },
      {
        bumblebee: {
          primary: '#f9d72e',
          'primary-focus': '#eec606',
          'primary-content': '#18192f',
          secondary: '#18192f',
          'secondary-focus': '#444563',
          'secondary-content': '#f9d72e',
          accent: '#34c573',
          'accent-focus': '#2a9a5b',
          'accent-content': '#ffffff',
          neutral: '#ffaf00',
          'neutral-focus': '#d69300',
          'neutral-content': '#656565',
          'base-100': '#ffffff',
          'base-200': '#d1d5da',
          'base-300': '#18192f',
          'base-content': '#f6f7f7',
        },
      },
      {
        dracula: {
          primary: '#ffb3d8',
          'primary-focus': '#ff80c0',
          'primary-content': '#1d1f25',
          secondary: '#b9ffb3',
          'secondary-focus': '#8bfe80',
          'secondary-content': '#1d1f25',
          accent: '#feffb2',
          'accent-focus': '#feff80',
          'accent-content': '#1d1f25',
          neutral: '#bfb8e5',
          'neutral-focus': '#908bad',
          'neutral-content': '#1d1f25',
          'base-100': '#30303d',
          'base-200': '#1d1f25',
          'base-300': '#d5ccff',
          'base-content': '#3f3d4c',
        },
      },
    ],
  },
};
